### PR TITLE
aripy

### PR DESCRIPTION
**Pull request by aleairaghi**
aggiornato a mia versione ....prova

### CODE REVIEW

**Comment by giorgio323323** [comment]
ARI è connessa alla rete. ho testato con un altro software.
Questa versione da i messaggi seguenti:

id mappa PDJZ
errore  [WinError 10061] No connection could be made because the target machine actively refused it
[WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
mystring !>p9600?
errore coda mov
errore  [WinError 10061] No connection could be made because the target machine actively refused it
[WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
errore  [WinError 10061] No connection could be made because the target machine actively refused it
[WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
errore  [WinError 10061] No connection could be made because the target machine actively refused it
[WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
errore  [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by aleairaghi** [comment]
non vedo il pezzo in cui arianna si presenza tramite udp......non è che sei
in test?


Il giorno mar 30 ott 2018 alle ore 21:25 giorgio323323 <
notifications@github.com> ha scritto:

**Comment by giorgio323323** [comment]
Cosa è test? Come lo setto ,?
Il 31/Ott/2018 09:02, "aleairaghi" <notifications@github.com> ha scritto:

**Comment by giorgio323323** [comment]
Ricevuto questo
Ciao
Il 07/Nov/2018 23:20, "aleairaghi" <notifications@github.com> ha scritto:

**Pull request merged**
